### ISSUE TITLE
Submit epic 1 datapackages to staging for testing

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#119]
Clear older dev catalogs and re-submit datapackages through dev VPC to test pipeline.
- [x] Run through dev (by ingest pipeline devs)
- [x] Run through staging (by ingest pipelien devs)
- [x] Run through staging (by CFDE test team)

Staging second pass by test team:
- [x] hmp
- [x] gtex
- [x] motrpac
- [x] kidsfirst
- [x] metabolomics
- [x] lincs
- [x] 4dn

**Comment by karlcz** [comment]
I adjusted this issue to be more general about both dev and staging environment tests of the same kind...

**Comment by karlcz** [comment]
I'm revising this issue to have less overlap with a centralized deployment checklist issue we have in the systems-infrastructure repo.

**Comment by karlcz** [comment]
I wonder if we still expect to have the test team run the 7 submissions and check off these TODO items, or if this issue is now a bit stale...

**Comment by ACharbonneau** [comment]
I am for sure going to test IDG. And I want to test at least a couple known ones. I can do all 7 old ones if you want. I'm a little more interested in testing some that I think shouldn't work tho. Given the manifests that some of the DCCs have given to me as done, I'm a little concerned about the variety of not what we were expecting data that they might try to push through obce they have the tool locally and I'm not a barrier to submission

**Comment by ACharbonneau** [comment]
@karlcz Where do I get the datapackages for the original 7?

**Comment by ACharbonneau** [comment]
have gotten script that finds them. Testing now

**Comment by ACharbonneau** [comment]
I'll put testing new stuff on its own issue.
