### ISSUE TITLE
implement, deploy and operate a cloud-based identifier s/w i/f for CFDE

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#28]
Start: 1/1/20
End: 1/1/21

Milestone: 5

POC: @mikedarcy 

- [ ] - https://github.com/nih-cfde/cfde-deriva/issues/11
- [ ] - https://github.com/nih-cfde/cfde-deriva/issues/12
- [ ] - https://github.com/nih-cfde/cfde-deriva/issues/13

**Comment by ACharbonneau** [comment]
ask mike about identifer service

**Comment by ACharbonneau** [comment]
moved to https://github.com/nih-cfde/planning-discussions/issues/1
