### ISSUE TITLE
System infrastructure deployment

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#44]
[system diagram](https://docs.google.com/presentation/d/1FJRSSkx3p8wpXoS8dmVr4FezLIa7YdUohWaOvPQVVGg/edit#slide=id.g7e218382c9_0_7)

waiting for STRIDES AWS accounts, but in the meantime

standup a VPC? need dedicated one for CFDE production deployment

UMB to set up local copy using our AWS account, Mike can provide access through firewall rules.

VPC environments? staging, devel, prod. Owned by STRIDES account

Need GLOBUS auth

**Comment by RLC-DCPPC** [comment]
- [ ] level 0 and level 1 C2M2 model
- [ ] ingested into Deriva catalog
- [ ] need a stable version of the catalog that HMP should be loaded into Deriva (need to loop in @jgaff )

**Comment by RLC-DCPPC** [comment]
- [ ] - Set up proxies
- [ ] - reserve words for Deriva SPI endpoints
- [ ] - security/auth for dashboard
- [ ] - depends on REST API between dashboards and Deriva

**Comment by RLC-DCPPC** [comment]
Hi @amahurkar and @carlkesselman . Just pointing you to this issue where we are tracking items we are working on. Can build formal sub-issues as needed.

**Comment by ACharbonneau** [comment]
give to infrastructure group

**Comment by ACharbonneau** [comment]
moved to infrastructure process doc issue
